Repository DFY-NCSU/slash-phase6, pull requests merged in 2024-11, with the labels that each got.

#28 Add support to costco
  src/configs_mt.py
  src/formattr.py
  src/main_streamlit.py
  src/scraper_ct.py
  src/scraper_mt.py
Labels: enhancement

#30 Test costco API
  tests/test_api_costco.py
  tests/test_api_ebay.py
  tests/test_api_walmart.py
Labels: enhancement

#31 Update some files
  CONTRIBUTING.md
  Code_Of_Conduct.md
  LICENSE.md
Labels: documentation

#32 Update the document to introduce our project
  assets/Slash-Phase6/2024-11-01_18.45.21.png
  assets/Slash-Phase6/2024-11-01_18.45.38.png
  assets/Slash-Phase6/2024-11-01_18.46.04.png
  assets/Slash-Phase6/2024-11-01_18.47.04.png
  assets/Slash-Phase6/2024-11-01_18.47.55.png
  assets/Slash-Phase6/2024-11-01_18.52.22.png
  docs/Code Description.md
  docs/Code Description_Phase-5.pdf
  docs/Improvements-phase5.md
  docs/Mini tutorials for use cases.md
  docs/Slash-Phase6.md
  docs/SoftwareDocumentation-Phase 5.md
Labels: documentation

#35 Write the Install Guide and update the Slash-Phase6.md
  INSTALL.md
  docs/Slash-Phase6.md
Labels: documentation

#38 Update the user case and logo
  README.md
  assets/slash.png
  assets/slash_new.png
  docs/Mini tutorials for use cases.md
Labels: documentation

#41 Update logical in `check_price` in test cases
  tests/test_api_bestbuy.py
  tests/test_api_ebay.py
  tests/test_api_target.py
  tests/test_api_walmart.py
Labels: bug

#42 fix bug for price
  tests/test_api_costco.py
Labels: bug

#43 format tests code
  tests/test_api_bestbuy.py
  tests/test_api_costco.py
  tests/test_api_ebay.py
  tests/test_api_general.py
  tests/test_api_target.py
  tests/test_api_walmart.py
  tests/test_feature.py
  tests/test_formatNumber.py
  tests/test_formatNumber_new.py
  tests/test_formatResults.py
  tests/test_formatResults_new.py
  tests/test_formatText.py
  tests/test_url_shortener.py
Labels: enhancement

#44 Add support in Frontend4costco
  src/pages/search.py
Labels: enhancement

#45 Finishing refactoring for target api and fix minor errors
  src/configs_mt.py
  src/scraper_ct.py
  src/scraper_mt.py
  src/scraper_tg.py
Labels: enhancement

#46 format src codes
  src/__init__.py
  src/configs.py
  src/configs_mt.py
  src/currency_conversion.py
  src/database.py
  src/formattr.py
  src/main.py
  src/main_streamlit.py
  src/models.py
  src/pages/login.py
  src/pages/logout.py
  src/pages/register.py
  src/pages/search.py
  src/pages/wishlist.py
  src/routers/auth.py
  src/routers/wish_list.py
  src/scraper.py
  src/scraper_ct.py
  src/scraper_mt.py
  src/scraper_tg.py
  src/url_shortener.py
Labels: enhancement

#47 Test/workflow
  .github/workflows/cov.yml
  .github/workflows/flake8.yml
  .github/workflows/python-app.yml
  .github/workflows/style.yml
  .github/workflows/syntax.yml
  README.md
  tests/test_api_general.py
Labels: enhancement

#48 Up readme
  README.md
  media/exp1.png
  media/exp2.png
  media/exp3.png
Labels: enhancement

#51 Dev
  .github/workflows/cov.yml
  .github/workflows/python-app.yml
  README.md
Labels: bug

#52 Update acknowledgement in readme
  README.md
Labels: enhancement

#50 Finished the video for presentation
  docs/Slash-Phase6.md
Labels: documentation

#53 Cleanup codes
  .github/workflows/cov.yml
  Project 3/CITATION.md
  Project 3/Project 3 Rubric.md
  Project 3/README.md
  src/configs.py
  src/configs_mt.py
  src/currency_conversion.py
  src/database.py
  src/formattr.py
  src/main.py
  src/main_streamlit.py
  src/models.py
  src/pages/login.py
  src/pages/search.py
  src/scraper.py
  src/scraper_ct.py
  src/scraper_mt.py
  src/scraper_tg.py
  tests/test_api_bestbuy.py
  tests/test_api_costco.py
  tests/test_api_ebay.py
  tests/test_api_walmart.py
  tests/test_formatNumber_new.py
  tests/test_formatResults_new.py
Labels: enhancement

#56 Clean up codes
  .github/workflows/cov.yml
  Project 3/CITATION.md
  Project 3/Project 3 Rubric.md
  Project 3/README.md
  README.md
  docs/Slash-Phase6.md
  src/configs.py
  src/configs_mt.py
  src/currency_conversion.py
  src/database.py
  src/formattr.py
  src/main.py
  src/main_streamlit.py
  src/models.py
  src/pages/login.py
  src/pages/search.py
  src/scraper.py
  src/scraper_ct.py
  src/scraper_mt.py
  src/scraper_tg.py
  tests/test_api_bestbuy.py
  tests/test_api_costco.py
  tests/test_api_ebay.py
  tests/test_api_walmart.py
  tests/test_formatNumber_new.py
  tests/test_formatResults_new.py
Labels: enhancement

#57 Contri
  .github/workflows/cov.yml
  .github/workflows/flake8.yml
  .github/workflows/python-app.yml
  .github/workflows/style.yml
  .github/workflows/syntax.yml
  README.md
Labels: enhancement
